import mongoose from "mongoose";

const studyPlanSchema = new mongoose.Schema({
    userId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User', 
        required: true 
    },
    examId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Exam', 
        required: true 
    },
    subject: { 
        type: String, 
        required: true 
    },
    generatedPlan: { 
        type: Array, 
        required: true 
    }, // Array of daily tasks generated by AI
    startDate: { 
        type: Date 
    },
    endDate: { 
        type: Date 
    }
}, { timestamps: true });

export default mongoose.model('StudyPlan', studyPlanSchema);